import React from 'react'
import { Link } from 'react-router-dom'

export default function Home() {
  return (
    <div>
      <h2>About: </h2>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Quam id leo in vitae turpis massa sed elementum. Laoreet sit amet cursus sit amet dictum. Quis imperdiet massa tincidunt nunc pulvinar sapien et. Donec massa sapien faucibus et molestie ac feugiat sed. Libero id faucibus nisl tincidunt. Amet porttitor eget dolor morbi non arcu. Interdum velit euismod in pellentesque massa placerat. Duis convallis convallis tellus id interdum velit laoreet id. Dis parturient montes nascetur ridiculus mus mauris vitae ultricies leo. Vestibulum lorem sed risus ultricies tristique nulla aliquet enim. Non quam lacus suspendisse faucibus interdum. Eget aliquet nibh praesent tristique magna sit amet purus. Imperdiet dui accumsan sit amet nulla facilisi morbi tempus iaculis. Diam ut venenatis tellus in metus vulputate. Odio facilisis mauris sit amet massa vitae tortor. Ac turpis egestas sed tempus urna et pharetra pharetra. Mauris commodo quis imperdiet massa tincidunt. In fermentum et sollicitudin ac.

Diam maecenas ultricies mi eget. Sed elementum tempus egestas sed sed risus pretium quam vulputate. Vitae tempus quam pellentesque nec nam aliquam. Purus viverra accumsan in nisl. Iaculis at erat pellentesque adipiscing commodo elit. At volutpat diam ut venenatis tellus in metus. Quis varius quam quisque id. Vel elit scelerisque mauris pellentesque pulvinar pellentesque habitant. At tellus at urna condimentum mattis pellentesque id nibh tortor. Vulputate sapien nec sagittis aliquam malesuada bibendum arcu. Convallis posuere morbi leo urna molestie at elementum.

Aliquam vestibulum morbi blandit cursus risus at ultrices. Vel pharetra vel turpis nunc. Tortor vitae purus faucibus ornare suspendisse sed. Commodo elit at imperdiet dui accumsan. Netus et malesuada fames ac. Scelerisque eu ultrices vitae auctor eu. Massa enim nec dui nunc mattis enim ut tellus. Etiam non quam lacus suspendisse faucibus interdum posuere lorem. Ultrices sagittis orci a scelerisque purus semper eget duis at. Interdum posuere lorem ipsum dolor sit. Tellus elementum sagittis vitae et. Proin fermentum leo vel orci porta non pulvinar. Odio eu feugiat pretium nibh ipsum consequat. Venenatis a condimentum vitae sapien. Tincidunt ornare massa eget egestas.

Ultrices vitae auctor eu augue ut lectus arcu bibendum. Non curabitur gravida arcu ac tortor dignissim. Lectus sit amet est placerat in egestas erat imperdiet. Pellentesque elit ullamcorper dignissim cras. Nibh sit amet commodo nulla facilisi nullam vehicula ipsum. Molestie ac feugiat sed lectus vestibulum. Amet commodo nulla facilisi nullam. Id donec ultrices tincidunt arcu non sodales neque sodales. Quam adipiscing vitae proin sagittis nisl rhoncus mattis rhoncus urna. Ultrices vitae auctor eu augue ut lectus. Lorem ipsum dolor sit amet consectetur adipiscing elit ut. Potenti nullam ac tortor vitae purus faucibus. Proin sed libero enim sed faucibus turpis in. Vel pretium lectus quam id leo in vitae turpis massa. Amet nisl purus in mollis nunc sed id semper. Id neque aliquam vestibulum morbi blandit. Urna nec tincidunt praesent semper feugiat nibh sed pulvinar. Imperdiet dui accumsan sit amet nulla facilisi morbi tempus iaculis. Metus dictum at tempor commodo ullamcorper a lacus. Sapien pellentesque habitant morbi tristique senectus et.

Blandit massa enim nec dui nunc. Sed risus pretium quam vulputate dignissim suspendisse in est. Pretium fusce id velit ut tortor pretium viverra suspendisse potenti. Nec feugiat nisl pretium fusce id. Sagittis id consectetur purus ut faucibus pulvinar elementum integer enim. Odio aenean sed adipiscing diam. Auctor augue mauris augue neque gravida in fermentum. Enim facilisis gravida neque convallis a cras semper. In eu mi bibendum neque egestas congue quisque egestas. Nam libero justo laoreet sit. Fames ac turpis egestas maecenas pharetra convallis. Non nisi est sit amet facilisis magna. Rhoncus dolor purus non enim. In metus vulputate eu scelerisque felis imperdiet proin. Lacus vel facilisis volutpat est velit. Id semper risus in hendrerit gravida.
</p>
    <Link to="/contactme">Contact Me</Link>
    </div>
  )
}
